In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn import metrics
from sklearn import datasets

In [2]:
digits = datasets.load_digits(as_frame = True)

In [3]:
digits

{'data':       pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
 0           0.0        0.0        5.0       13.0        9.0        1.0   
 1           0.0        0.0        0.0       12.0       13.0        5.0   
 2           0.0        0.0        0.0        4.0       15.0       12.0   
 3           0.0        0.0        7.0       15.0       13.0        1.0   
 4           0.0        0.0        0.0        1.0       11.0        0.0   
 ...         ...        ...        ...        ...        ...        ...   
 1792        0.0        0.0        4.0       10.0       13.0        6.0   
 1793        0.0        0.0        6.0       16.0       13.0       11.0   
 1794        0.0        0.0        1.0       11.0       15.0        1.0   
 1795        0.0        0.0        2.0       10.0        7.0        0.0   
 1796        0.0        0.0       10.0       14.0        8.0        1.0   
 
       pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
 0        

In [4]:
# flatten the images
n_samples = len(digits.images)
df = digits.images.reshape((n_samples, -1))

In [5]:
df.shape

(1797, 64)

In [6]:
x = df
y = digits["target"]

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)

In [8]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [21]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(x_train, y_train)

print(rf.score(x_train, y_train))

y_pred_rf = rf.predict(x_test)
print(metrics.accuracy_score(y_test, y_pred_rf))

1.0
0.9796296296296296


In [10]:
print(metrics.confusion_matrix(y_pred_rf, y_test))
print('-----')
print(metrics.classification_report(y_pred_rf, y_test))

[[52  0  0  0  0  0  0  0  0  0]
 [ 0 49  0  0  0  0  0  0  2  0]
 [ 0  1 47  0  0  0  0  0  0  0]
 [ 0  0  0 51  0  0  0  0  0  1]
 [ 1  0  0  0 60  0  0  0  0  0]
 [ 0  0  0  1  0 64  1  0  0  1]
 [ 0  0  0  0  0  1 52  0  0  0]
 [ 0  0  0  0  0  0  0 54  0  1]
 [ 0  0  0  2  0  0  0  0 41  0]
 [ 0  0  0  0  0  1  0  1  0 56]]
-----
              precision    recall  f1-score   support

           0       0.98      1.00      0.99        52
           1       0.98      0.96      0.97        51
           2       1.00      0.98      0.99        48
           3       0.94      0.98      0.96        52
           4       1.00      0.98      0.99        61
           5       0.97      0.96      0.96        67
           6       0.98      0.98      0.98        53
           7       0.98      0.98      0.98        55
           8       0.95      0.95      0.95        43
           9       0.95      0.97      0.96        58

    accuracy                           0.97       540
   macro avg 

In [19]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier()

mlp.fit(x_train, y_train)

print(mlp.score(x_train, y_train))

y_pred_mlp = mlp.predict(x_test)
print(metrics.accuracy_score(y_test, y_pred_mlp))

1.0
0.9740740740740741


In [18]:
print(metrics.confusion_matrix(y_pred_mlp, y_test))
print('-----')
print(metrics.classification_report(y_pred_mlp, y_test))

[[52  0  0  0  0  0  1  0  0  0]
 [ 0 49  0  0  0  0  0  0  0  0]
 [ 1  1 47  1  0  0  0  0  0  0]
 [ 0  0  0 51  0  0  0  0  0  0]
 [ 0  0  0  0 60  0  0  0  0  0]
 [ 0  0  0  1  0 64  0  0  1  0]
 [ 0  0  0  0  0  1 52  0  0  0]
 [ 0  0  0  0  0  0  0 54  0  0]
 [ 0  0  0  1  0  0  0  0 42  1]
 [ 0  0  0  0  0  1  0  1  0 58]]
-----
              precision    recall  f1-score   support

           0       0.98      0.98      0.98        53
           1       0.98      1.00      0.99        49
           2       1.00      0.94      0.97        50
           3       0.94      1.00      0.97        51
           4       1.00      1.00      1.00        60
           5       0.97      0.97      0.97        66
           6       0.98      0.98      0.98        53
           7       0.98      1.00      0.99        54
           8       0.98      0.95      0.97        44
           9       0.98      0.97      0.97        60

    accuracy                           0.98       540
   macro avg 

In [13]:
mlp = MLPClassifier(verbose=True)

mlp.fit(x_train, y_train)

print(mlp.score(x_train, y_train))

y_pred_mlp = mlp.predict(x_test)
print(metrics.accuracy_score(y_test, y_pred_mlp))

Iteration 1, loss = 2.33797055
Iteration 2, loss = 1.83542767
Iteration 3, loss = 1.44237110
Iteration 4, loss = 1.15182607
Iteration 5, loss = 0.93837757
Iteration 6, loss = 0.77791417
Iteration 7, loss = 0.65607573
Iteration 8, loss = 0.56015304
Iteration 9, loss = 0.48575156
Iteration 10, loss = 0.42590390
Iteration 11, loss = 0.37843568
Iteration 12, loss = 0.33950893
Iteration 13, loss = 0.30666641
Iteration 14, loss = 0.27966457
Iteration 15, loss = 0.25589154
Iteration 16, loss = 0.23537288
Iteration 17, loss = 0.21803592
Iteration 18, loss = 0.20155174
Iteration 19, loss = 0.18745327
Iteration 20, loss = 0.17484604
Iteration 21, loss = 0.16333674
Iteration 22, loss = 0.15328482
Iteration 23, loss = 0.14397986
Iteration 24, loss = 0.13520178
Iteration 25, loss = 0.12747839
Iteration 26, loss = 0.12050694
Iteration 27, loss = 0.11395597
Iteration 28, loss = 0.10803984
Iteration 29, loss = 0.10248956
Iteration 30, loss = 0.09748890
Iteration 31, loss = 0.09272404
Iteration 32, los

In [14]:
from sklearn.model_selection import GridSearchCV

grid_params = {
    "activation":["relu","logistic"],
    "hidden_layer_sizes":[(100,),(200,),(100,100,)],
    "alpha":[0.0001,0.005],
    "learning_rate":["constant","adaptive"],
    "max_iter":[1000]
}

gs = GridSearchCV(
    MLPClassifier(),
    grid_params,
    cv = 2
)

gs_results = gs.fit(x_train, y_train)

print(gs_results.best_score_)
print(gs_results.best_estimator_)
print(gs_results.best_params_)

0.9657959758184562
MLPClassifier(alpha=0.005, hidden_layer_sizes=(200,), max_iter=1000)
{'activation': 'relu', 'alpha': 0.005, 'hidden_layer_sizes': (200,), 'learning_rate': 'constant', 'max_iter': 1000}


In [20]:
mlp = MLPClassifier(alpha=0.005, hidden_layer_sizes=(200,), max_iter=1000)

mlp.fit(x_train, y_train)

print(mlp.score(x_train, y_train))

y_pred_mlp = mlp.predict(x_test)
print(metrics.accuracy_score(y_test, y_pred_mlp))

1.0
0.9814814814814815
