In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn import metrics
from sklearn import datasets

In [2]:
digits = datasets.load_digits(as_frame = True)

In [5]:
n_samples = len(digits.images)
df = digits.images.reshape((n_samples, -1))

In [9]:
x = df
y = digits["target"]

In [10]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [18]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(x_train_scaled, y_train)

print(rf.score(x_train_scaled, y_train))

y_pred = rf.predict(x_test_scaled)
print(metrics.accuracy_score(y_test, y_pred))

1.0
0.9777777777777777


In [19]:
print(metrics.confusion_matrix(y_pred, y_test))

[[52  0  0  0  0  0  0  0  0  0]
 [ 0 50  0  0  0  1  0  0  1  0]
 [ 0  0 47  0  0  0  0  0  0  0]
 [ 0  0  0 52  0  0  0  0  0  1]
 [ 1  0  0  0 60  1  0  0  0  1]
 [ 0  0  0  0  0 63  1  0  0  1]
 [ 0  0  0  0  0  1 52  0  0  0]
 [ 0  0  0  0  0  0  0 54  0  0]
 [ 0  0  0  2  0  0  0  0 42  0]
 [ 0  0  0  0  0  0  0  1  0 56]]


In [20]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier()

mlp.fit(x_train_scaled, y_train)

print(mlp.score(x_train_scaled, y_train))

y_pred = mlp.predict(x_test_scaled)
print(metrics.accuracy_score(y_test, y_pred))

1.0
0.9814814814814815


In [21]:
print(metrics.confusion_matrix(y_pred, y_test))

[[53  0  0  0  0  0  0  0  0  0]
 [ 0 50  0  0  0  0  0  0  0  0]
 [ 0  0 47  1  0  0  0  0  0  0]
 [ 0  0  0 51  0  0  0  0  0  0]
 [ 0  0  0  0 60  0  0  0  0  0]
 [ 0  0  0  1  0 64  1  0  1  0]
 [ 0  0  0  0  0  1 52  0  0  0]
 [ 0  0  0  0  0  0  0 54  0  0]
 [ 0  0  0  1  0  0  0  0 42  2]
 [ 0  0  0  0  0  1  0  1  0 57]]


In [22]:
mlp = MLPClassifier(verbose = True)

mlp.fit(x_train_scaled, y_train)

print(mlp.score(x_train_scaled, y_train))

y_pred = mlp.predict(x_test_scaled)
print(metrics.accuracy_score(y_test, y_pred))

Iteration 1, loss = 2.14269144
Iteration 2, loss = 1.70878318
Iteration 3, loss = 1.36506763
Iteration 4, loss = 1.09726422
Iteration 5, loss = 0.89032818
Iteration 6, loss = 0.73478779
Iteration 7, loss = 0.61578677
Iteration 8, loss = 0.52581021
Iteration 9, loss = 0.45591908
Iteration 10, loss = 0.40108109
Iteration 11, loss = 0.35791718
Iteration 12, loss = 0.32194704
Iteration 13, loss = 0.29207663
Iteration 14, loss = 0.26695403
Iteration 15, loss = 0.24516612
Iteration 16, loss = 0.22611235
Iteration 17, loss = 0.20964209
Iteration 18, loss = 0.19465836
Iteration 19, loss = 0.18150256
Iteration 20, loss = 0.16989913
Iteration 21, loss = 0.15945397
Iteration 22, loss = 0.15015797
Iteration 23, loss = 0.14132589
Iteration 24, loss = 0.13375637
Iteration 25, loss = 0.12649369
Iteration 26, loss = 0.11976647
Iteration 27, loss = 0.11373365
Iteration 28, loss = 0.10787740
Iteration 29, loss = 0.10270528
Iteration 30, loss = 0.09771407
Iteration 31, loss = 0.09300239
Iteration 32, los

In [25]:
mlp = MLPClassifier(hidden_layer_sizes = (100,100,))

mlp.fit(x_train_scaled, y_train)

print(mlp.score(x_train_scaled, y_train))

y_pred = mlp.predict(x_test_scaled)
print(metrics.accuracy_score(y_test, y_pred))

1.0
0.975925925925926
