In [4]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
%matplotlib inline

In [5]:
df = pd.read_csv("stars.csv")

In [6]:
df.shape

(240, 7)

In [7]:
df.head()

Temperature (K)  Luminosity(L/Lo)  Radius(R/Ro)  Absolute magnitude(Mv)  \
0             3068          0.002400        0.1700                   16.12   
1             3042          0.000500        0.1542                   16.60   
2             2600          0.000300        0.1020                   18.70   
3             2800          0.000200        0.1600                   16.65   
4             1939          0.000138        0.1030                   20.06   

   Star type Star color Spectral Class  
0          0        Red              M  
1          0        Red              M  
2          0        Red              M  
3          0        Red              M  
4          0        Red              M

In [8]:
df.corr()

Temperature (K)  Luminosity(L/Lo)  Radius(R/Ro)  \
Temperature (K)                1.000000          0.393404      0.064216   
Luminosity(L/Lo)               0.393404          1.000000      0.526516   
Radius(R/Ro)                   0.064216          0.526516      1.000000   
Absolute magnitude(Mv)        -0.420261         -0.692619     -0.608728   
Star type                      0.411129          0.676845      0.660975   

                        Absolute magnitude(Mv)  Star type  
Temperature (K)                      -0.420261   0.411129  
Luminosity(L/Lo)                     -0.692619   0.676845  
Radius(R/Ro)                         -0.608728   0.660975  
Absolute magnitude(Mv)                1.000000  -0.955276  
Star type                            -0.955276   1.000000

In [9]:
df["Star type"].value_counts()

0    40
1    40
2    40
3    40
4    40
5    40
Name: Star type, dtype: int64

In [10]:
x = df.drop(["Star type"], axis = 1)
y = df["Star type"]

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 200)

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 2)
model_knn = knn.fit(x_train, y_train)
y_pred = model_knn.predict(x_test)

ValueError: could not convert string to float: 'Blue'

In [34]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df['Star color'] = label_encoder.fit_transform(df['Star color'])
df['Spectral Class'] = label_encoder.fit_transform(df['Spectral Class'])

In [35]:
x = df.drop(["Star type"], axis = 1)
y = df["Star type"]

In [36]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 200)

In [37]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 2)
model_knn = knn.fit(x_train, y_train)
y_pred = model_knn.predict(x_test)

In [38]:
from sklearn import metrics

print(model_knn.score(x_train, y_train))

cm = metrics.confusion_matrix(y_test, y_pred)
print(cm)

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

0.8385416666666666
[[ 4  0  0  0  0  0]
 [ 6  1  0  0  0  0]
 [ 0  0 10  0  0  0]
 [ 0  1  4  2  0  0]
 [ 0  0  0  0  7  3]
 [ 0  0  0  0  8  2]]
Accuracy: 0.5416666666666666


In [39]:
#x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 200)

In [40]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler().fit(x_train)

x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [41]:
df.head()

Temperature (K)  Luminosity(L/Lo)  Radius(R/Ro)  Absolute magnitude(Mv)  \
0             3068          0.002400        0.1700                   16.12   
1             3042          0.000500        0.1542                   16.60   
2             2600          0.000300        0.1020                   18.70   
3             2800          0.000200        0.1600                   16.65   
4             1939          0.000138        0.1030                   20.06   

   Star type  Star color  Spectral Class  
0          0          10               5  
1          0          10               5  
2          0          10               5  
3          0          10               5  
4          0          10               5

In [42]:
knn = KNeighborsClassifier(n_neighbors = 10)
model_knn = knn.fit(x_train_scaled, y_train)
y_pred = model_knn.predict(x_test_scaled)

print(model_knn.score(x_train_scaled, y_train))

cm = metrics.confusion_matrix(y_test, y_pred)
print(cm)

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

0.9427083333333334
[[ 4  0  0  0  0  0]
 [ 0  7  0  0  0  0]
 [ 0  0 10  0  0  0]
 [ 0  0  0  6  1  0]
 [ 0  0  0  1  9  0]
 [ 0  0  0  0  1  9]]
Accuracy: 0.9375


In [43]:
#model_knn2.predict_proba(x_test2)

In [44]:
#x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

#scaler = MinMaxScaler().fit(x_train)
#x_train_scaled = scaler.transform(x_train)
#x_test_scaled = scaler.transform(x_test)

from sklearn.model_selection import GridSearchCV

grid_params = {
    "n_neighbors":[1,2,3,4,5,6,7,8,9,10,20]
}

gs = GridSearchCV(
    KNeighborsClassifier(),
    grid_params,
    cv = 20
)

gs_results = gs.fit(x_train_scaled, y_train)

In [45]:
print(gs_results.best_score_)
print(gs_results.best_estimator_)
print(gs_results.best_params_)

0.985
KNeighborsClassifier(n_neighbors=1)
{'n_neighbors': 1}


In [46]:
y_pred = gs_results.predict(x_test_scaled)

print(gs_results.score(x_train_scaled, y_train))

cm = metrics.confusion_matrix(y_test, y_pred)
print(cm)

print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

1.0
[[ 4  0  0  0  0  0]
 [ 0  7  0  0  0  0]
 [ 0  0 10  0  0  0]
 [ 0  0  0  7  0  0]
 [ 0  0  0  0 10  0]
 [ 0  0  0  0  1  9]]
Accuracy: 0.9791666666666666


In [47]:
from sklearn.model_selection import GridSearchCV

grid_params = {
    "n_neighbors":[1,2,3,4,5,6,7,8,9,10,20],
    "metric":["euclidean","manhattan"],
}

gs = GridSearchCV(
    KNeighborsClassifier(),
    grid_params,
    cv = 20
)

gs_results = gs.fit(x_train_scaled, y_train)

In [48]:
print(gs_results.best_score_)
print(gs_results.best_estimator_)
print(gs_results.best_params_)

0.9949999999999999
KNeighborsClassifier(metric='manhattan', n_neighbors=1)
{'metric': 'manhattan', 'n_neighbors': 1}


In [49]:
y_pred = gs_results.predict(x_test_scaled)

print(gs_results.score(x_train_scaled, y_train))

cm = metrics.confusion_matrix(y_test, y_pred)
print(cm)

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

1.0
[[ 4  0  0  0  0  0]
 [ 0  7  0  0  0  0]
 [ 0  0 10  0  0  0]
 [ 0  0  0  7  0  0]
 [ 0  0  0  0 10  0]
 [ 0  0  0  0  1  9]]
Accuracy: 0.9791666666666666


In [50]:
df_new = pd.read_csv("stars.csv")

In [51]:
star_col_dummies = pd.get_dummies(df_new['Star color'], dtype=float)
spec_cla_dummies = pd.get_dummies(df_new['Spectral Class'], dtype=float)

df_new = df_new.drop(['Star color', 'Spectral Class'], axis=1)

df_new = pd.concat([df_new, star_col_dummies], axis=1)
df_new = pd.concat([df_new, spec_cla_dummies], axis=1)

In [52]:
df_new.head()

Temperature (K)  Luminosity(L/Lo)  Radius(R/Ro)  Absolute magnitude(Mv)  \
0             3068          0.002400        0.1700                   16.12   
1             3042          0.000500        0.1542                   16.60   
2             2600          0.000300        0.1020                   18.70   
3             2800          0.000200        0.1600                   16.65   
4             1939          0.000138        0.1030                   20.06   

   Star type  Blue  Blue   Blue White  Blue white  Blue white   ...  white  \
0          0   0.0    0.0         0.0         0.0          0.0  ...    0.0   
1          0   0.0    0.0         0.0         0.0          0.0  ...    0.0   
2          0   0.0    0.0         0.0         0.0          0.0  ...    0.0   
3          0   0.0    0.0         0.0         0.0          0.0  ...    0.0   
4          0   0.0    0.0         0.0         0.0          0.0  ...    0.0   

   yellow-white  yellowish    A    B    F    G    K    M    O  
0           0.0        0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  
1           0.0        0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  
2           0.0        0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  
3           0.0        0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  
4           0.0        0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  

[5 rows x 31 columns]

In [53]:
x = df.drop(["Star type"], axis = 1)
y = df["Star type"]

In [54]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 200)

In [55]:
scaler = MinMaxScaler().fit(x_train)
x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [56]:
grid_params = {
    "n_neighbors":[1,2,3,4,5,7,9,17],
    "metric":["euclidean","manhattan","minkowski"],
}

gs = GridSearchCV(
    KNeighborsClassifier(),
    grid_params,
    cv = 10
)

gs_results = gs.fit(x_train_scaled, y_train)

print(gs_results.best_score_)
print(gs_results.best_estimator_)
print(gs_results.best_params_)

0.9949999999999999
KNeighborsClassifier(metric='manhattan', n_neighbors=1)
{'metric': 'manhattan', 'n_neighbors': 1}


In [57]:
y_pred = gs_results.predict(x_test_scaled)

print(gs_results.score(x_train_scaled, y_train))

cm = metrics.confusion_matrix(y_test, y_pred)
print(cm)

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

1.0
[[ 4  0  0  0  0  0]
 [ 0  7  0  0  0  0]
 [ 0  0 10  0  0  0]
 [ 0  0  0  7  0  0]
 [ 0  0  0  0 10  0]
 [ 0  0  0  0  1  9]]
Accuracy: 0.9791666666666666


In [58]:
df2 = df

label_encoder = LabelEncoder()
df2['Star color'] = label_encoder.fit_transform(df['Star color'])
df2['Spectral Class'] = label_encoder.fit_transform(df['Spectral Class'])

df2['Temperature (K)'] = np.log(df2['Temperature (K)'])
df2['Luminosity(L/Lo)'] = np.log(df2['Luminosity(L/Lo)'])
df2['Radius(R/Ro)'] = np.log(df2['Radius(R/Ro)'])

x = df2.drop(["Star type"], axis = 1)
y = df2["Star type"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 200)

scaler = MinMaxScaler().fit(x_train)
x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)

grid_param = {
    "n_neighbors":[1,2,3,4,5,6,7,8,17],
    "metric":["euclidean","manhattan"],
}

gs = GridSearchCV(
    KNeighborsClassifier(),
    grid_params4,
    cv = 20
)

gs_results = gs.fit(x_train_scaled, y_train)

print(gs_results.best_score_)
print(gs_results.best_estimator_)
print(gs_results.best_params_)



NameError: name 'grid_params4' is not defined

In [59]:
y_pred = gs_results.predict(x_test_scaled)

print(gs_results.score(x_train_scaled, y_train))

cm = metrics.confusion_matrix(y_test, y_pred)
print(cm)

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

0.7291666666666666
[[ 4  0  0  0  0  0]
 [ 0  7  0  0  0  0]
 [ 0  0 10  0  0  0]
 [ 0  0  0  2  0  5]
 [ 0  0  0  0  0 10]
 [ 0  0  0  0  0 10]]
Accuracy: 0.6875


In [60]:
df = pd.read_csv("stars.csv")

label_encoder = LabelEncoder()
df['Star color'] = label_encoder.fit_transform(df['Star color'])
df['Spectral Class'] = label_encoder.fit_transform(df['Spectral Class'])

x = df.drop(["Star type"], axis = 1)
y = df["Star type"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, stratify = df["Star type"])

scaler = MinMaxScaler().fit(x_train)
x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)

grid_params = {
    "n_neighbors":[1,2,3,4,5,6,7,8,9,10,20]
}

gs = GridSearchCV(
    KNeighborsClassifier(),
    grid_params,
    cv = 20
)

gs_results = gs.fit(x_train_scaled, y_train)

In [61]:
y_pred = gs_results.predict(x_test_scaled)

print(gs_results.score(x_train_scaled, y_train))

cm = metrics.confusion_matrix(y_test, y_pred)
print(cm)

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

1.0
[[8 0 0 0 0 0]
 [0 8 0 0 0 0]
 [0 0 8 0 0 0]
 [0 0 0 8 0 0]
 [0 0 0 1 7 0]
 [0 0 0 0 1 7]]
Accuracy: 0.9583333333333334
